### ISSUE TITLE
PPR Finder results not showing activities when searching by location name

### ISSUE THREAD

**Issue by Darrenef** [CityOfPhiladelphia/parks-rec-finder#216]
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

### Observed Behavior
> Steps to Reproduce

_Searching by location does not yield a list of activities for the site._
Users must click on "Locations" tab after doing search, which is counter-intuitive.

1. Search by activity or location name: East Passyunk Community Center
2. Results: "No activities were found. Try the Locations tab above"

### Screenshot

![finder - search for activities by location](https://user-images.githubusercontent.com/37077239/37170294-757fa148-22d8-11e8-8631-d32ec4f89a37.jpg)

###Proposed solutions
_Option 1:_ search location for approved programs.  If there are approved programs, list as activities.  This is ideal because it will show actual results under activities.

_Option 2_: default to "Location" tab (showing 2 locations for East Passyunk area) instead of "Activities" (showing no results).  User can then click on a location and scroll down for programs.  This is not ideal as it requires more clicks and searching.

###Screenshot (of proposed solution Option 1)

![finder - search for activities by location proposed](https://user-images.githubusercontent.com/37077239/37171835-2984d86c-22dd-11e8-90b4-0634e95e3adf.jpg)

**Comment by timwis** [comment]
Hi @Darrenef, thanks for posting the issue with such detail, and I apologise for our delay in replying. I know exactly what you mean, and I can see how that's confusing. The reason is we're searching the name and description of the activities and locations. There aren't any activities with "east passyunk" in the name or description. We could show all activities for any matching locations, but I actually think that might be even more confusing (just a hypothesis though). I think what you held up for option 2 makes the most sense to me. We had trouble doing it that way the first time around but I think we have a way to do it soon.

**Comment by timwis** [comment]
Fixed in v2! :)
