### ISSUE TITLE
Make the layout mobile-friendly

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/parks-rec-finder#220]
Here's what we're after:
![illustration of desired mobile-friendly layout](https://i.imgur.com/CJRwUqC.png)

Notice:
- the category name and filters are fixed
- the site footer disappears on mobile
- a toggle botton appears fixed at the bottom on mobile

[Here's a close implementation](https://codepen.io/timwis/pen/VXxKKo?editors=1010) using CSS Grid. Ideally, I think, we'd use the **SASS Reference** of [foundation's xy grid](https://foundation.zurb.com/sites/docs/xy-grid.html), if for no other reason than it lets us put it all in `App.vue` and apply it to the `list` and `map` in all the pages.

That part, at least, is all sass/css. Where it gets trickier is in toggling between the list and map on mobile. The simplest solution is for the toggle button to change a class in a container, and use `display: none/block` to show/hide the list or map, depending on the class. That would work, but we'll need the button to also send a signal to the Leaflet instance to reset itself (`map.invalidateSize()`) because if leaflet is initialised on an element that has no width and height, it will be broken until you reset it.

Another approach is to conditionally render the list or the map based on a JavaScript variable (instead of a class). That would make using the application on mobile a bit faster because it would only render the list or the map, not both. But may take a moment longer to switch. Not sure either would be very noticeable but it's not tested. [Here's some more info on the trade-offs](https://vuejs.org/v2/guide/conditional.html#v-if-vs-v-show). This latter approach would likely require the JavaScript to know whether the screen is narrow, since we'd only want to conditionally render on small screens (wide screens show both the list _and_ the map). We could use [Window.watchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) for a CSS-like media query.

**Comment by karissademi** [comment]
I ended up doing something slightly different. Instead of show/hiding the map, it is the sidebar content that is toggled. The map naturally wants to fall under the sidebar content on mobile. Hiding/showing the sidebar content means the map can render at X height on pageload, making the toggle button nice and snappy when it is touched. 

The allowable area for the map height is calculated from the height of the client at the time of render and updated if the browser is resized. There is a "magic" number that is subtracted from the client height, which is the height of the header and footer on mobile. That's really the only downside I see to this method, but there might be others I'm not thinking of.
