### ISSUE TITLE
About this activity (description), is currently working where available.

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#253]
@andrewviren to provide test case.

**Comment by timwis** [comment]
It's working fine for me. [Example](http://ppr-finder-v2.surge.sh/#/activity/youth-kickball/59765884b849a55152401d55). Screenshot below. There are only 220 activities that have a `programdescriptionshort` in the database.

![screen shot 2018-06-07 at 6 30 28 am 1](https://user-images.githubusercontent.com/761444/41094452-580f23b4-6a1c-11e8-9d26-a9e191279f03.png)

@andyviren let me know if you're seeing something different; otherwise let's close this issue.

**Comment by andrewviren** [comment]
Yes. We haven't scaled up to editing all program descriptions yet. 220 is correct. Fine to close @sarahall
